
var login=document.getElementById("in"),main=document.getElementById("main"),logout=document.getElementById("out"),play=document.getElementById("play"),again=document.getElementById("again"),canvas=document.getElementById("canvas"),context=canvas.getContext("2d"),balls=[],_R=15,_N=1,_C=0,_W=!1,_S=1E3,_V=.025,_SC=0,_T,batdaudem=!1,tick_toc=59,_P=!1,tt;canvas.width=window.innerWidth;canvas.height=window.innerHeight;window.onresize=function(){canvas.width=window.innerWidth;canvas.height=window.innerHeight};
play.addEventListener("click",start);again.addEventListener("click",start);canvas.addEventListener("mousedown",function(a){for(var b=0;b<balls.length;b++)balls[b].dist(a.clientX,a.clientY)<balls[b].r&&0<balls[b].v&&(balls[b].v=0,_SC+=10,_C++,_C==_N?(_W=!0,batdaudem=!1,setTimeout(function(){_N++;50<_S&&(_S-=50);1>_V&&(_V+=.025);init()},1E3)):batdaudem=!0)});
canvas.addEventListener("touchend",function(a){a=a.changedTouches[0];for(var b=0;b<balls.length;b++)balls[b].dist(a.clientX,a.clientY)<balls[b].r&&0<balls[b].v&&(balls[b].v=0,_SC+=10,_C++,_C==_N?(_W=!0,batdaudem=!1,setTimeout(function(){_N++;50<_S&&(_S-=50);1>_V&&(_V+=.025);init()},1E3)):batdaudem=!0)});e.preventDefault();function myrd(a,b){b=void 0===b?0:b;return Math.floor(Math.random()*(a-b)+b)}function myhsl(){return"hsl("+myrd(360)+",100%,50%)"}
function myhsla(a){return"hsl("+myrd(360)+",100%,50%,"+a+")"}function init(){balls=[];_V=.025;_C=0;_W=!1;tick_toc=59;batdaudem=!1;_T=1+Math.floor(.5*_N);for(var a=0;a<_N;a++)balls.push(new myBall(myrd(canvas.width),myrd(canvas.height),0,myhsl(),_V))}
function myBall(a,b,c,d,f){this.x=a;this.y=b;this.c=d;this.r=c;this.toy=this.tox=-1;this.v=f;this.show=function(){context.strokeStyle="#3b3b3b";context.fillStyle=this.c;context.beginPath();context.arc(this.x,this.y,this.r,0,2*Math.PI);context.fill();context.lineWidth=2;context.stroke()};this.to=function(){this.x=(this.tox-this.x)*this.v+this.x;this.y=(this.toy-this.y)*this.v+this.y};this.settoXY=function(a,b){this.tox=a;this.toy=b};this.dist=function(a,b){return Math.sqrt(Math.pow(this.x-a,2)+Math.pow(this.y-
b,2))}}function start(){_P=!0;_N=1;_SC=0;login.style.display="none";main.style.display="block";logout.style.display="none";init();update()}
function update(){context.clearRect(0,0,canvas.width,canvas.height);context.textAlign="center";if(_P){context.font="30px Baloo";context.fillStyle="green";context.fillText(_SC,50,40);batdaudem&&(tick_toc--,0==tick_toc&&(_T--,tick_toc=59,0>_T&&(tick_toc=_T=0,_P=!1)),context.fillStyle="red",context.fillText(_T+":"+tick_toc,canvas.width-100,40));for(var a=0;a<balls.length;a++)_W&&0<balls[a].r&&balls[a].r--,!_W&&balls[a].r<_R&&balls[a].r++,balls[a].show(),0<balls[a].tox&&balls[a].to();tt=requestAnimationFrame(update)}else cancelAnimationFrame(tt),
logout.style.display="block",main.style.display="none"}setInterval(function(){for(var a=0;a<balls.length;a++)balls[a].settoXY(myrd(canvas.width),myrd(canvas.height))},_S);
